name: jobprovider
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  velocity_x: 3.5.1
  get_storage: ^2.0.3
  flutter_verification_code: ^1.1.6
  google_nav_bar: ^5.0.6
  banner_carousel: ^1.2.1
  flutter_dash: ^1.0.0
  custom_sliding_segmented_control: ^1.7.3
  retrofit: ^3.3.1
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  flutter_calendar_carousel: ^2.4.1
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.5+3
  cool_alert: ^1.1.0
  flutter_bounce: ^1.1.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.4
  flutter_local_notifications: ^9.2.0
  double_back_to_close_app: ^2.1.0
  flutter_launcher_icons: ^0.11.0






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: any
  retrofit_generator: 4.2.0
  flutter_gen_runner: any


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/fastracklogo.png"

flutter:
  uses-material-design: true
  assets:
     - assets/images/getstartedbg.png
     - assets/images/cvimg.png
     - assets/images/whitebg.png
     - assets/images/forgetpasswordimg.png
     - assets/images/verifyemailimg.png
     - assets/images/vehicle.png
     - assets/images/drawericon.png
     - assets/images/bannerimg.png
     - assets/images/donemark.png
     - assets/images/profilepic.jpg
     - assets/images/dollar_sign.png
     - assets/images/waitingimg.png
     - assets/images/timerimg.png
     - assets/images/fastracklogo.png
     - assets/images/splashbg.png
     - assets/images/appicon.png
     - assets/images/appfastlogo.png

  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/poppins_semibold.ttf
     - family: PoppinsRegular
       fonts:
         - asset: assets/fonts/poppins_regular.ttf
     - family: PoppinsMedium
       fonts:
         - asset: assets/fonts/poppins_medium.ttf
     - family: PoppinsLight
       fonts:
         - asset: assets/fonts/poppins_light.ttf


